### ISSUE TITLE
I would like channel icons on the left side

### ISSUE THREAD

**Issue by robert-john-small** [speculatrix/tvh_epg#1]

**Comment by speculatrix** [comment]
I have done this for freesat, but it is a hack, because there doesn't seem to be a way to do this in the API, so I simply hack in a direct link to the images at https://github.com/Elky666/TVLogos

I'm not going to close this until I can fix it properly through the image cache in the TVH server.

**Comment by speculatrix** [comment]
I have asked on the forum how to do this correctly
https://tvheadend.org/boards/5/topics/34354

**Comment by speculatrix** [comment]
I now use the TVH channel icons, but this seems slower. Perhaps I should make it user selectable whether to have it served by the web server serving the EPG, or have them served by TVH?

**Comment by speculatrix** [comment]
I recently improved this, so that you can specify a different base URL for picons.
also, if the channel name ends in +1, it will use the picon for the normal channel. yes, there are some picons for +1 but there's sufficient broken ones that I decided safest is best.
