### ISSUE TITLE
slightly better documentation for less technical users

### ISSUE THREAD

**Issue by Guyverix** [speculatrix/tvh_epg#11]
I have been attempting to get this installed, but have been running into problems and some confusion.  My hope would be to get slightly better docs on how to set this up correctly.  Once I get this running, I will try to create a PR or something like this since I suspect that many people are going to want to use this EPG :)

**Comment by Guyverix** [comment]
another thing that might be useful would be a defaulted tvh_epg_settings.ini file that has all the defaults defined so that it is easier to know exactly what needs to be changed.  Looking in the debug output kinda shows, but it is not user friendly.

**Comment by speculatrix** [comment]
Hi,
in theory when the program is first run it will create the settings and tells you some sensible defaults to put in. however, that does assume you know what sort of things will work, so I agree it does need some more documentation to explain things.

**Comment by speculatrix** [comment]
BTW, if you pull the latest version you'll need to go into setup again as there are a bunch of new settings

**Comment by speculatrix** [comment]
check the other issues here to see if people have already had similar questions answered
