### ISSUE TITLE
Exception trying to access tvh_epg website

### ISSUE THREAD

**Issue by ranger81** [speculatrix/tvh_epg#14]
Hi,
I have installed your script as you described. I receive the following error in the Apache2 error_log after trying to access the website. Do you have any hint for me?

Thanks

`[Sat Apr 16 20:24:17.917076 2022] [http:error] [pid 18068:tid 2960081920] [client ipaddr] AH02429: Response header name '<!--' contains invalid characters, aborting request
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3.9/tempfile.py", line 390, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/python_errors/tmp650_53in.html'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/cgi-bin/tvh_epg.py", line 1615, in <module>
    web_interface()
  File "/usr/lib/cgi-bin/tvh_epg.py", line 1550, in web_interface
    html_page_header()
  File "/usr/lib/cgi-bin/tvh_epg.py", line 1334, in html_page_header
    if BG_COL_PAGE in MY_SETTINGS[SETTINGS_SECTION] and MY_SETTINGS.get(SETTINGS_SECTION, BG_COL_PAGE) != '':
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'user'
[Sat Apr 16 20:26:47.557605 2022] [http:error] [pid 18068:tid 2968474624] [client ipaddr] AH02429: Response header name '<!--' contains invalid characters, aborting request`

**Comment by speculatrix** [comment]
did you make the directory /var/www/html/python_errors
and make it group www-data and group writable? (or whatever httpd runs as)

once you've done that, if python throws a stack trace it will write a file there which you can access as http//example/python_errors

**Comment by speculatrix** [comment]
also, you need to have created the directory /var/lib/tvh_epg/
and make it group www-data and group writable? (or whatever httpd runs as)

that should allow you to go into the settings menu and set the values to your local services. the EPG cgi-bin doesn't need to run on the same server as TVH, which might be a good thing if you're running TVH on a low powered device like a Pi.

**Comment by speculatrix** [comment]
since I've not had any followup questions, I'm closing this ticket.
