### ISSUE TITLE
I would like two-tone (or multi-tone) colours with the different channels to make the rows more obvious

### ISSUE THREAD

**Issue by robert-john-small** [speculatrix/tvh_epg#2]

**Comment by speculatrix** [comment]
I have just pushed a change which allows you to set the page background colour and I will consider how best to make some rows highlighted

**Comment by speculatrix** [comment]
I am not really that sure this is needed, because if you choose the right bg colour then the epg rows are quite strongly visible across the screen.

Let me know if you still want this feature. @robert-john-small

**Comment by speculatrix** [comment]
no response from requester, so closing ticket, but will consider accessibility and visibility issues in future developments
