### ISSUE TITLE
I would like to be able to see more information when I mouse over things

### ISSUE THREAD

**Issue by robert-john-small** [speculatrix/tvh_epg#4]

**Comment by speculatrix** [comment]
I now have a mouse hover feature giving the program summary if there is one. I moved the (R) to the left of the title so that the floating pane doesn't obscure the record function.

Let me know if this is to your satisfaction.

**Comment by speculatrix** [comment]
I added a mouse hover message saying "Record" if you hover over the "R" symbol.
